src/Component.cpp, src/Components/Appendage.cpp, src/Components/CircleShape.cpp, src/Components/DynamicBody.cpp, src/Components/Line.cpp, src/Components/Location.cpp, src/Components/RectangleShape.cpp, src/Components/Sprite.cpp, src/Components/StaticSegment.cpp, src/Entity.cpp, src/EntityFactory.cpp, src/Event.cpp, src/ResourceManager.cpp, src/System.cpp
As described [here](https://google.github.io/styleguide/cppguide.html#Namespaces).
=> Conform to google style guide namespace convention.

CMakeLists.txt
Switch to suitable C++ compilation option for MSVC with a minimal addition of logic in CMakeList.
=> Smooth MSVC build

include/Game.h, include/Systems/PhysicsSystem.h, include/View.h, include/Views/PlayerView.h, src/Game.cpp, src/Systems/PhysicsSystem.cpp, src/View.cpp, src/Views/PlayerView.cpp
Allows the physical simulation to run consistently across machines. Fixes #18.
=> Implement fixed time step for physics

include/Components/LinearForce.h, include/Components/Location.h, include/Components/Sprite.h, include/EntityFactory.h, include/Systems/PhysicsSystem.h, include/View.h, src/Components/LinearForce.cpp, src/Components/Location.cpp, src/Components/Sprite.cpp, src/EntityFactory.cpp, src/Systems/PhysicsSystem.cpp, src/Systems/SpriteRenderSystem.cpp, src/View.cpp, src/Views/PlayerView.cpp
Creates a linear force component which is used for fans. Resolves #14.
=> Linear force

include/Components/Appendage.h, include/Systems/PhysicsSystem.h, include/View.h, include/Views/PlayerView.h, src/Systems/ControlCenter.cpp, src/Systems/PhysicsSystem.cpp, src/View.cpp, src/Views/PlayerView.cpp
Removed unnecessary arguments and print statements. Also made minor changes to ControlCenter so forces make more sense with the new fixed-step physics system.
=> Cleaned Code

include/Components/LinearForce.h, include/Views/PlayerView.h, src/EntityFactory.cpp, src/Systems/ControlCenter.cpp, src/Systems/PhysicsSystem.cpp, src/View.cpp, src/Views/PlayerView.cpp
This resolves #33. The demo level from our initial presentation has been implemented in a rudimentary way.
=> Implement Demo Level

README.md
=> Update README to be more descriptive

CMakeLists.txt
Current change is from @narrative.
=> Fix gason in Windows MSVC

include/Constants.h, include/ViewManager.h, include/Views/LevelView.h, src/Views/LevelView.cpp
Renamed PlayerView to LevelView and moved STATUSBAR_HEIGHT from LevelView.h to Constants.h
=> LevelView Refactor

data/level1.json, data/level2.json, include/Level.h, include/Systems/DialogueSystem.h, include/Views/LevelView.h, src/Level.cpp, src/Systems/DialogueSystem.cpp, src/Views/LevelView.cpp
Updated DialogueSystem to allow specifying the amount of time to show each individual piece of dialogue. Also updated the level reader and level files to take advantage of this.
=> Dialogue system update

include/Views/LevelView.h, src/Views/LevelView.cpp
- Rename playerview_render_system to main_render_system
- Capitalize first letter of status bar methods for consistency
Close #79
=> Improve naming

include/Views/LevelView.h, src/Views/LevelView.cpp
Resolves #80. Also includes some very minor refactoring in PlayerView, mostly just renaming the dialog_box to dialogue_box because it's now only for dialogue and not a general-purpose dialog box.
=> Numeric display for status bar resources

src/Views/LevelView.cpp
This simplified some math when doing level design
=> use viewports for camera

README.md
Simple name change from "Jetpack Game" to "Serene".
=> Update game title in README

src/Systems/ParticleSystem.cpp
=> Prevent upper bound on distribution from being less than 0

src/Systems/SoundManager.cpp
Also tweaked attenuation and volume on some other spatial sounds so they're not so overpowering.
=> Laser sounds were OP, so they've been nerfed in this patch.

src/Systems/ParticleSystem.cpp, src/Views/LevelView.cpp
This fixes the issue causing there to be fewer particles per emitter as the number of emitters increased.
Close #119
=> Fix bug related to not generating enough particles

data/snippet.json, src/Views/LevelMenuView.cpp, src/Views/WinMenuView.cpp
Copied and edited story from Tao's powerpoint into the json file.
=> Put story snippets into json file

src/LogicCenter.cpp
Clean console text by disabling JSON test when level file reading.
=> Disable JSON test

Serene_external_libraries.txt
Include a TXT file listing any external libraries needed (+website where the library can be found) as required.
=> Include a TXT file listing any external libraries
